 
# Ref: https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser
blank_issues_enabled: false  # default: true
contact_links:
- name: Community Support ğŸ¤·
  url: https://www.reddit.com/r/safing
  about: Please ask any questions you have here
- name: Code of Conduct ğŸ“
  url: https://github.com/safing/portmaster/blob/develop/CODE_OF_CONDUCT.md
  about: Be nice to other community members â¤
