 
# Ref: https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser
blank_issues_enabled: true  # default: true
contact_links:
- name: User Interface Issues ğŸ’»
  url: https://github.com/safing/portmaster-ui/issues/new/choose
  about: Report any issues or feature requests for the Portmaster UI here
- name: Support Requests & Community ğŸ¤·
  url: https://www.reddit.com/r/safing
  about: Ask for support and any questions you might have on reddit.
- name: Code of Conduct ğŸ“
  url: https://github.com/safing/portmaster/blob/develop/CODE_OF_CONDUCT.md
  about: Be nice to other community members â¤
